fixed the css file for removing the hover effect from heading
GoodGameRuler/unitrack_v3 pull request #39
Opened 2024-05-29 08:15 UTC by TheAshutoshGupta

![Screenshot 2024-05-29 134356](https://github.com/GoodGameRuler/unitrack_v3/assets/125827121/4a8881dc-7afd-4013-953e-f08a33a919e1)

Fixing #37

2024-05-29 08:44 UTC, jennifermtan requested changes

2024-05-29 08:44 UTC, jennifermtan commented on app/degreePlanner/detailPlanner.css
> +/* .semesterRow:hover {
Hi, please delete the code instead of commenting it out.

2024-05-29 08:50 UTC, jennifermtan commented
Hi @TheAshutoshGupta, please rename the PR to be more specific to the issue. Thanks :)

2024-05-29 09:05 UTC, TheAshutoshGupta commented
> Hi @TheAshutoshGupta, please rename the PR to be more specific to the issue. Thanks :)

deleted the css lines, and also specified the PR name

2024-05-29 09:31 UTC, jennifermtan approved these changes
LGTM :)

2024-05-30 09:14 UTC, GoodGameRuler commented
Approving changes. @TheAshutoshGupta please refer to branch naming rules. I will approve this PR however, next time I will require the branch naming scheme be followed.

2024-05-30 12:43 UTC, merged